apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rollouts-demo
resources:
  - ../../base
images:
  - name: argoproj/rollouts-demo
    newTag: blue
patches:
  - path: patch-rollout.yaml
