apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: rollouts-demo
resources:
  - ../../base
images:
  - name: rollouts-demo
    newName: 364641874932.dkr.ecr.ap-south-1.amazonaws.com/ibs-demo-apps
    newTag: green
patches:
  - path: patch-rollout.yaml
